version: '3'

services:

  database:
    image: postgres
    restart: always
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hmstream
    ports: 
      - 5432:5432
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment: 
      - ADMINER_DEFAULT_SERVER=database